### PR TITLE
Ciclovia in Bogota

### PR DESCRIPTION
**Pull request by angoca**
This is a new project we are going to map in Colombia

### CODE REVIEW

**Comment by joto** [comment]
The link must be to the raw json file, not the github rendering of it.

**Comment by angoca** [comment]
Shame on me. Sorry, I already corrected it.

**Comment by angoca** [comment]
I already corrected the data types array problem.

**Comment by joto** [comment]
> I already corrected the data types array problem.

Apparently not, it still doesn't work.

**Comment by angoca** [comment]
It wasn't the array, it was just that I put the version as string, not integer.

**Pull request merged**
