### PR TITLE
Traffic_sign Europe East (Inclusion of RS)

### PR DESCRIPTION
**Pull request by yopaseopor**
Split of Europe data project

### CODE REVIEW

**Comment by joto** [comment]
Ids are not unique.

**Comment by yopaseopor** [comment]
Sorry for the mistake. I have missed change one of the id's. Now all are unique. I hope it will be correct

**Comment by joto** [comment]
Now your json is broken.

**Comment by yopaseopor** [comment]
Fixed all the missing characters.

**Pull request merged**
